env:
  commonjs: true
  es6: true
  node: true
  jest: true
extends: "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
rules:
  linebreak-style: 0
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - never
