name: deploy

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Copy file to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ORG_PROD_CICD_SSH_HOST }}
        username: ${{ secrets.ORG_PROD_CICD_SSH_USERNAME }}
        password: ${{ secrets.ORG_PROD_CICD_SSH_PASSWORD }}
        source: "./*,!.git"
        target: ${{ secrets.PROD_REMOTE_DIR }}
        overwrite: true

    - name: Run service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORG_PROD_CICD_SSH_HOST }}
        username: ${{ secrets.ORG_PROD_CICD_SSH_USERNAME }}
        password: ${{ secrets.ORG_PROD_CICD_SSH_PASSWORD }}
        script: |
          . ~/.profile
          cd ${{ secrets.PROD_REMOTE_DIR }}
          yarn install --frozen-lockfile --production=true
          sudo systemctl restart seminara